### ISSUE TITLE
Truecolor support

### ISSUE THREAD

**Issue by toastal** [andrwb/vim-lapis256#1]
I've used this theme in 256 color support for years, but I'd like to use some features in with 24-bit color support. By enabling `termguicolors`, the theme breaks. I'd love to keep using the same scheme even in 24-bits. If I have time, I may fork and set these colors, but it looks like others are using a fair amount of indirection to support both 256 and truecolor and I don't read enough VimL to follow at a glance. Is there a plan to support both?

**Comment by andrwb** [comment]
Glad the 256 has worked for you, but alas no plans for 24 bits nor familiarity with VimL to support both at the moment.
